---
- name: create content views
  include_tasks: '_create_content_view.yml'
  with_items: "{{ foreman_content_views }}"
  loop_control:
    loop_var: content

- name: "Ensure content view version is in all environments"
  include: cv_subtask.yml
  loop: "{{ foreman_content_views }}"
  when:
   - item.lifecycle_environments is defined
  