---
- name: Add Controller host
  host:
    name:                   "{{ __controller_host_item.name | mandatory }}"
    new_name:               "{{ __controller_host_item.new_name | default(omit, true) }}"
    description:            "{{ __controller_host_item.description | default(omit, true) }}"
    inventory:              "{{ __controller_host_item.inventory | mandatory }}"
    enabled:                "{{ __controller_host_item.enabled | default(omit) }}"
    state:                  "{{ __controller_host_item.state | default(controller_state | default('present')) }}"
    variables:              "{{ __controller_host_item.variables | default(omit, true) | regex_replace('[ ]{2,}','') }}"

    # Role Standard Options
    controller_host:        "{{ controller_hostname | default(omit, true) }}"
    controller_username:    "{{ controller_username | default(omit, true) }}"
    controller_password:    "{{ controller_password | default(omit, true) }}"
    controller_oauthtoken:  "{{ controller_oauthtoken | default(omit, true) }}"
    controller_config_file: "{{ controller_config_file | default(omit, true) }}"
    validate_certs:         "{{ controller_validate_certs | default(omit) }}"
  loop: "{{ controller_hosts }}"
  loop_control:
    loop_var: __controller_host_item
  no_log: "{{ controller_configuration_hosts_secure_logging }}"
...
