---
- name: 'Create Lifecycle Environments'
  theforeman.foreman.lifecycle_environment:
    username: "{{ username | default(omit) }}"
    password: "{{ password | default(omit) }}"
    server_url: "{{ server_url | default(omit) }}"
    validate_certs: "{{ validate_certs | default(omit) }}"
    organization: "{{ organization }}"
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }}"
    prior: "{{ item.prior }}"
    label: "{{ item.label | default(omit) }}"
    state: present
  with_items:
    - "{{ lifecycle_environments }}"
