---
# Update Controller Projects
- name: Run Controller project update
  project_update:
    name:                     "{{ __project_update_update_item.name }}"
    organization:             "{{ __project_update_update_item.organization.name | default(__project_update_update_item.organization | default(omit, true)) }}"
    wait:                     "{{ __project_update_update_item.wait | default(omit) }}"
    interval:                 "{{ __project_update_update_item.interval | default(1) }}"
    timeout:                  "{{ __project_update_update_item.timeout | default(omit, true) }}"

    # Role Standard Options
    controller_username:      "{{ controller_username | default(omit, true) }}"
    controller_password:      "{{ controller_password | default(omit, true) }}"
    controller_oauthtoken:    "{{ controller_oauthtoken | default(omit, true) }}"
    controller_host:          "{{ controller_hostname | default(omit, true) }}"
    controller_config_file:   "{{ controller_config_file | default(omit, true) }}"
    validate_certs:           "{{ controller_validate_certs | default(omit) }}"
  loop: "{{ controller_projects }}"
  loop_control:
    loop_var: "__project_update_update_item"
  no_log: "{{ controller_configuration_project_update_secure_logging }}"
  when:
    - controller_projects is defined
    - __project_update_update_item.update
...
