---
- name: Add controller group
  group:
    name:                           "{{ controller_groups_item.name | mandatory }}"
    new_name:                       "{{ controller_groups_item.new_name | default(omit, true) }}"
    description:                    "{{ controller_groups_item.description | default(omit, true) }}"
    inventory:                      "{{ controller_groups_item.inventory | mandatory }}"
    variables:                      "{{ controller_groups_item.variables | default(omit, true) | regex_replace('[ ]{2,}','') }}"
    hosts:                          "{{ controller_groups_item.hosts | default(omit, true) }}"
    children:                       "{{ controller_groups_item.children | default(omit, true) }}"
    preserve_existing_hosts:        "{{ controller_groups_item.preserve_existing_hosts | default(omit) }}"
    preserve_existing_children:     "{{ controller_groups_item.preserve_existing_children | default(omit) }}"
    state:                          "{{ controller_groups_item.state | default(controller_state | default('present')) }}"

    # Role Standard Options
    controller_username:            "{{ controller_username | default(omit, true) }}"
    controller_password:            "{{ controller_password | default(omit, true) }}"
    controller_oauthtoken:          "{{ controller_oauthtoken | default(omit, true) }}"
    controller_host:                "{{ controller_hostname | default(omit, true) }}"
    controller_config_file:         "{{ controller_config_file | default(omit, true) }}"
    validate_certs:                 "{{ controller_validate_certs | default(omit) }}"
  loop: "{{ controller_groups }}"
  loop_control:
    loop_var: controller_groups_item
  no_log: "{{ controller_configuration_group_secure_logging }}"
...
