---
- name: Create Ansible Controller Team
  team:
    name:                     "{{ __controller_team_item.name | mandatory }}"
    new_name:                 "{{ __controller_team_item.new_name | default(omit, true) }}"
    description:              "{{ __controller_team_item.description | default(omit, true) }}"
    organization:             "{{ __controller_team_item.organization.name | default( __controller_team_item.organization ) | mandatory }}"
    state:                    "{{ __controller_team_item.state | default(controller_state | default('present')) }}"

    # Role Standard Options
    controller_config_file:   "{{ controller_config_file | default(omit, true) }}"
    controller_host:          "{{ controller_hostname | default(omit, true) }}"
    controller_password:      "{{ controller_password | default(omit, true) }}"
    controller_username:      "{{ controller_username | default(omit, true) }}"
    controller_oauthtoken:    "{{ controller_oauthtoken | default(omit, true) }}"
    validate_certs:           "{{ controller_validate_certs | default(omit) }}"
  loop: "{{ controller_teams }}"
  loop_control:
    loop_var: __controller_team_item
  no_log: "{{ controller_configuration_teams_secure_logging }}"
...
