---
- name: Download Subscription Manifest from Red Hat Customer Portal
  redhat.satellite.redhat_manifest:
    uuid: "{{ manifest_uuid }}"
    username: "{{ rhsm_username }}"
    password: "{{ rhsm_password }}"
    path: "{{ manifest_path }}"
  when: manifest_download

- name: Upload Subscription Manifest to Foreman
  redhat.satellite.subscription_manifest:
    username: "{{ username }}"
    password: "{{ password }}"
    server_url: "{{ server_url }}"
    validate_certs: "{{ validate_certs | default(omit) }}"
    organization: "{{ organization }}"
    manifest_path: "{{ manifest_path }}"
    state: present
